#!/usr/bin/env python3
"""src_fingerprint.py -- deterministic content fingerprint of the walker's build inputs.

WHY THIS EXISTS
----------------
The per-era build harness (scripts/build-era-walkers.{ps1,sh}) used to skip rebuilding
an era whenever the sidecar's recorded `walkerGitSha` equalled repo HEAD -- so an
UNCOMMITTED walker source fix rebuilt zero binaries, and HEAD churned on every
unrelated artifacts commit even when nothing walker-relevant changed (the literal
mechanism behind the 3-of-6-walkers failure). This script replaces that git-SHA-keyed
skip with a CONTENT-keyed one: it hashes exactly the files that affect the walker
binary's behavior (walker/src/**, walker/CMakeLists.txt, the netmsg-table generator,
and the schemas/ proto family) and prints one stable SHA256 hex digest. Two runs
against an unchanged tree print the same line; touching any covered byte changes it,
regardless of git commit boundaries.

WHAT IS COVERED
----------------
  - walker/src/**  (every file, recursively) EXCLUDING netmsg_table.generated.inc,
    which is PER-ERA regenerated by gen_netmsg_table.py from that era's binaries --
    it is an OUTPUT of the era pin, not a build INPUT, and the era pin itself is
    captured separately (walker-manifest.json's hl2sdkPin). Hashing it here would
    make the fingerprint churn per-era even when no walker source changed.
  - walker/CMakeLists.txt              (the build definition itself)
  - walker/tools/gen_netmsg_table.py   (produces the excluded .inc above; a change
    to the GENERATOR is a real behavior change even though its OUTPUT is excluded)
  - schemas/*.proto                    (the wire contract the walker emits against;
    top-level only, non-recursive -- matches the literal `schemas/*.proto` glob)

CRLF-INSENSITIVITY
-------------------
The windows/linux build paths check out the SAME source tree through different git
`core.autocrlf` normalization, and the linux build path additionally CRLF-normalizes
the tree. To keep the fingerprint identical across both platforms' checkouts, every
file's bytes are hashed with all `\r` bytes stripped before hashing -- see
`_read_normalized` below.

USAGE
-----
  python walker/tools/src_fingerprint.py

Prints exactly one line: a 64-character lowercase hex SHA256 digest. No other output
on success. Pure standard library (hashlib, pathlib, sys) -- no third-party
dependency, so it runs identically from a bare git checkout before any Python
environment is provisioned (CMake invokes it with a bare `python3`/`python`, and the
build scripts invoke it the same way).
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

# Files that are build OUTPUTS, not INPUTS: regenerated per-era from that era's
# binaries by gen_netmsg_table.py, so their content tracks the era pin, not the
# walker source. Excluded by filename (there is exactly one, directly under
# walker/src/); see the module docstring "WHAT IS COVERED".
_EXCLUDED_FILENAMES = {"netmsg_table.generated.inc"}


def _repo_root() -> Path:
    # walker/tools/src_fingerprint.py -> tools -> walker -> repo root. Resolved
    # from __file__ (not cwd) so the script is safe to invoke from anywhere,
    # exactly as CMake's execute_process and the build scripts do.
    return Path(__file__).resolve().parents[2]


def _read_normalized(path: Path) -> bytes:
    # Strip EVERY \r byte before hashing, per the module docstring's
    # CRLF-INSENSITIVITY note. Stripping unconditionally (rather than a
    # \r\n-only replace) is simpler and strictly more permissive, and the two
    # are equivalent for every file actually covered here (no source file in
    # this tree legitimately contains a bare \r).
    return path.read_bytes().replace(b"\r", b"")


def _covered_files(repo_root: Path) -> list[Path]:
    walker_dir = repo_root / "walker"
    src_dir = walker_dir / "src"
    schemas_dir = repo_root / "schemas"

    files: list[Path] = []

    for path in src_dir.rglob("*"):
        if not path.is_file():
            continue
        if path.name in _EXCLUDED_FILENAMES:
            continue
        files.append(path)

    files.append(walker_dir / "CMakeLists.txt")
    files.append(walker_dir / "tools" / "gen_netmsg_table.py")
    files.extend(schemas_dir.glob("*.proto"))

    return files


def compute_fingerprint(repo_root: Path) -> str:
    entries: list[tuple[str, str]] = []
    for path in _covered_files(repo_root):
        relpath = path.relative_to(repo_root).as_posix()  # stable across OS
        file_hash = hashlib.sha256(_read_normalized(path)).hexdigest()
        entries.append((relpath, file_hash))

    entries.sort(key=lambda pair: pair[0])

    # Fold the sorted (relpath, file-hash) list into one digest via a canonical,
    # unambiguous per-entry encoding: relpath, NUL, file hash, LF. NUL cannot
    # appear in a relpath and file_hash is fixed-width hex, so this cannot
    # collide across different (relpath, hash) entry lists.
    digest = hashlib.sha256()
    for relpath, file_hash in entries:
        digest.update(relpath.encode("utf-8"))
        digest.update(b"\0")
        digest.update(file_hash.encode("ascii"))
        digest.update(b"\n")

    return digest.hexdigest()


def main() -> int:
    print(compute_fingerprint(_repo_root()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
