// NetMessages registry traversal. See netmsg_walk.h.
//
// SOURCE: the live INetworkMessages registry is EMPTY headless on every era
// (populating it needs an engine Init that AVs on the partial boot), so the
// pin-static kNetMsgTable (generated by tools/gen_netmsg_table.py from the pinned
// net-message .proto enums) is the SOLE source of channels. The walker never
// reads the live runtime registry — see "WHY NOT the live registry" at
// CollectNetMessages below.
//
// (Note: an earlier revision carried clean-room INetworkMessages /
// IProtobufBinding / NetMessageInfo_t vtable mirrors for a never-taken live-registry
// read path; they were removed as dead code — recover from git history if a
// non-crashing registration trigger is ever found.)
#include "netmsg_walk.h"

#include "loader.h"
#include "util.h"  // Str()

#include "network_messages.pb.h"
#include "walker_output.pb.h"

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

namespace wpb = cs2::schema_tracker::v0;

namespace cs2_schema_walker {

namespace {

// The PIN-STATIC id->type table derived from the pinned net-message .proto enums.
// Defines `struct NetMsgTableEntry { const char* channel; int id;
// const char* type; }` and `static const NetMsgTableEntry kNetMsgTable[]`. Generated
// by walker/tools/gen_netmsg_table.py — regenerate on an hl2sdk pin change.
#include "netmsg_table.generated.inc"

// One emitted entry.
struct Entry {
  std::int32_t id;
  std::string proto_type;
};

// Build channel -> [entries] from the PIN-STATIC table. Entries within a channel
// are NOT yet sorted (callers sort).
//
// WHY NOT the live INetworkMessages registry: it is ALWAYS empty in the headless walk
// (populating it needs ~the whole engine Init, which AVs — see the header /
// engine_boot.cpp), so it would add nothing. Worse, reading it means calling
// INetworkMessages vtable slots (FindNetworkMessageById@30) whose layout is the
// b8dcaf14 pin's — on an OTHER-era build (e.g. the 2023 baseline, or any older per-pin
// era) that slot is a DIFFERENT function and the call ACCESS-VIOLATES. So we do NOT
// touch the runtime registry at all; the static table is the sole source on every era.
// If a future non-crashing registration trigger lands, re-add a registry read here
// GATED to the matching pin/vtable (and SEH-guarded) — never an ungated vtable call.
void CollectNetMessages(const InProcessEnvironment& /*env*/,
                        std::map<std::string, std::vector<Entry>>* by_channel) {
  by_channel->clear();
  for (const NetMsgTableEntry& e : kNetMsgTable) {
    (*by_channel)[e.channel].push_back({e.id, e.type});
  }
}
}  // namespace

bool WalkNetworkMessages(const InProcessEnvironment& env,
                         wpb::NetworkMessagesWalk* out, std::string* /*err*/) {
  out->Clear();
  std::map<std::string, std::vector<Entry>> by_channel;
  CollectNetMessages(env, &by_channel);

  for (auto& kv : by_channel) {
    std::vector<Entry>& entries = kv.second;
    // Within a channel, sort by (id, proto_type) for determinism.
    std::sort(entries.begin(), entries.end(), [](const Entry& a, const Entry& b) {
      if (a.id != b.id) return a.id < b.id;
      return a.proto_type < b.proto_type;
    });
    wpb::NetworkChannel* chan = out->add_channels();
    chan->set_name(kv.first);
    for (const Entry& e : entries) {
      wpb::NetworkMessageEntry* m = chan->add_messages();
      m->set_id(e.id);
      m->set_proto_message_type(e.proto_type);
    }
  }
  return true;
}

}  // namespace cs2_schema_walker
